INSERT INTO suppliers (supplier_type,name,order_frequency) VALUES
('Game','ACD Distribution','Weekly'),
('Toys','Aero Motion, Inc.','Yearly'),
('Game','Alliance Game Distributors','Bi-Weekly'),
('Hobby','Atlas Brush Co.','Quarterly'),
('Mini Cases','Battle Foam','Special Order'),
('Gundams','Bluefin','Monthly'),
('CA Glue','Bob Smith','Bi-Monthly'),
('Slot Car','Carrera','6 Months'),
('RC','Common Sense RC','Monthly'),
('Pranks','Creative Products','Yearly'),
('Craft','Darice Inc.','Bi-Monthly'),
('Science Kits','Discover With Dr.Cool','Yearly'),
('Science Kits','Elenco','Yearly'),
('Puzzles','EuroGraphics Puzzles','Quarterly'),
('Models','Fascinations Inc.','Quarterly'),
('Game/ Model','Games Workshop','Weekly'),
('Toys','GiantMicrobes, Inc.','6-months'),
('Games','GTS Distribution','Quarterly'),
('Hobby','Horizon Hobby Rockets','Monthly'),
('Hobby','Horizon Hobby, Inc.','Weekly'),
('Puzzles','IMEX Model Co.','Yearly'),
('General','John N. Hansen Co., INC.','6 Months'),
('RC','JR Americas','Special Order'),
('Magazines','Kalmbach Media','Yearly'),
('Greeting Cards','Leanin'' Tree','6 Months'),
('Puzzles','Leanin'' Tree Puzzles','6 Months'),
('Games','Lion Rampant Imports','Special Order'),
('Toys','Magnum Enterprises','N/A'),
('Puzzles','Maynard''s','N/A'),
('Toys','Melissa & Doug','6 Months'),
('Puzzles/ Game','Outset Media','6 Months'),
('Gift','Pitkin Stearns (Sand Art)','N/A'),
('Kites','Premier Kites & Designs','Yearly'),
('Puzzles','Professor Puzzle','Bi-Monthly'),
('books','Quarto Group','N/A'),
('Puzzles/ Games','Ravensburger','6 Months'),
('Toys','Safari Ltd.','Quarterly'),
('Games','Southern Hobby Supply','Special Order'),
('Puzzles','Springbock','6 Months'),
('Hobby','Stevens International','Monthly'),
('Puzzles','SunsOut, Inc.','6 Months'),
('Coin supplies','Tonka Hobby Supply','6 Months'),
('Toys','Toysmith','6 Months'),
('RC','Traxxas','Weekly'),
('Models','Ugears US','Quarterly'),
('Train','Walthers','Bi-Quarterly'),
('Game','What do you Meme','6 Months'),
('Toys','WOWTOYZ','Yearly'),
('Swords','WUU JAU & Neptune Trading','N/A'),
('Gift','Zen Magnets LLC.','N/A'),
('Magic/ Toy','Fantasma Toys','N/A')
ON CONFLICT (name) DO UPDATE SET
  supplier_type=EXCLUDED.supplier_type,
  order_frequency=EXCLUDED.order_frequency,
  updated_at=now();
